project:
  type: website
  output-dir: docs

website:
  title: "Languages of the World Analysis"

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    
title: "Languages of the World: Mapping Diversity and Endangerment"
author: "Zakaria Laraki, Luc Dinh"